var profiles =[
    [
        {"Designation" : 	"President-D.H.M.A."},
        {"image" : "images/Profile_Pics/Mukesh_Sachdeva.jpg"},
        {"Name" :	"Sh. Mukesh Sachdeva"},
        {"Father's Name" :  "Sh. Gurcharan Lal Sachdeva"},
        {"Date of Birth" :	"30/04/1956"},
        {"Resident Address" :	"262, Bhera Enclave, Paschim Vihar, Delhi-110063"},
        {"Firm Name" :	"M/s. Sach Fab Creation Pvt. Ltd."},
        {"Office Address" :	"905, IInd Floor, Kucha Kabil Attar, Chandni Chowk, Delhi-06"},
        {"Contact No." : "011-49121494, 9811109054"},
        {"E-Mail" :	"msachdeva262@gmail.com"},
        {"Occupation" :	"Embriodery (Cloth)"},
        {"Nationality" : "Indian"},
        {"Language Known" :	"Hindi, English"},
        {"Social Activities" :	"Secretary-Textile Market Association Kucha Kabil Attar, Delhi-06"},
        
    ],
    [
        {"Designation" : 	"General Secretary -D.H.M.A."},
        {"image" : "images/Profile_Pics/ShriBhagwan_Bansal.jpeg"},
        {"Name" : "Sh. Shribhagwan Bansal"},
        {"Father's Name" :	"Late Sh. Krishan Kumar Bansal"},
        {"Date of Birth" :	"20/09/1963"},
        {"Resident Address" :	"BN-III (West), Shalimar Bagh, Delhi-110088"},
        {"Firm Name" :	"M/s. K.S. Textiles"},
        {"Office Address" :	"Shop No.-14, Shanker Bazar, Katra Shahanshai, Chandni Chowk, New Delhi-06"},
        {"Contact No." :	"011-49876983, 9811441557"},
        {"E-Mail" :	"shobhitbansal87@gmail.com, shribhagwanbansal1963@gmail.com"},
        {"Occupation" :	"Business (Ladies Suits)"},
        {"Nationality" :	"Indian"},
        {"Language Known" :	"Hindi, English"},
        {"Social Activities" :	"General Secretary- of Katra Shahanshai Chandni Chowk."},
        
    ],
    [
        {"Designation" :	"Senior Vice President-D.H.M.A."},
        {"image" : "images/Profile_Pics/Bheem_sain_dhingra.jpg"},
        {"Name" :	"Sh. Bhim Sen Dhingra"},
        {"Father Name" :	"Late. Ram Lal Dhingra"},
        {"Date of Birth" :	"04/02/1959"},
        {"Firm Address" :	"1073, Ist Floor, Gali Langrewali, Maliwara, Delhi-06"},
        {"Residence Address" :	"H-3/10, Gali No.-1, Model Town-II, Delhi"},
        {"Mob." :	"23276603, 9810001443"},
        {"Occupation" :	"Deal in Gray Fabrics for Exports"},
        {"Nationality" : 	"Indian"},
        {"Language Known" :	"Hindi, English"},
        {"Education Qualification" :	"B.A. (Hons.) from Delhi University"},
    ],
    [
        {"Designation" : 	"Vice President-D.H.M.A."},
        {"image" : "images/Profile_Pics/Suman_Aneja.jpeg"},
        {"Name" :	"Sh. Suman Aneja"},
        {"Father's Name" :	"Late. Sohan Lal Aneja"},
        {"Resident Address" :	"B-2/206, Pashchim Vihar, Delhi-63"},
        {"Firm Name" :	"M/s. Aneja Sarees"},
        {"Office Address" :	"4786-4787, Ram Bazar, Cloth Market, Delhi-06"},
        {"Contact No." :	"011-41329920, 9313499313"},
        {"Occupation" :	"Wholesale clothes"},
        {"Nationality" :	"Indian"},
        {"Language Known" :	"Hindi, English"},
        {"Education Qualification" :	"Graduate"},
        
    ],
    [
        {"Designation" :	"Secretary-D.H.M.A."},
        {"image" : "images/Profile_Pics/Anil_Saini_C.jpg"},
        {"Name" :	"Sh. Anil Saini"},
        {"Father's Name" :	"Late Tara Chand Saini"},
        {"Firm" :	"M/s. Menka & Co."},
        {"Firm Address" :	"887/14 & 815/6, Kucha Kabil Attar, Chandni Chowk, Delhi-06"},
        {"Residence Address" :	"C-83, Sector-23, Noida-201301, U.P"},
        {"Contact No." :	"011-47097626, 9899327333"},
        {"E-mail" :	"anilsaini453@gmail.com"},
        {"Business" : 	"Commission Agent"},
        {"Language Known" : 	"Hindi, English"},
        {"Education Qualification" : 	"Graduate"}
    ],
    [
        {"Designation" : 	"Jt. Secretary-D.H.M.A."},
        {"image" : "images/Profile_Pics/Ram_Prakash_Bansal.jpg"},
        {"Name" :	"Sh. Ram Parkash Bansal"},
        {"Father's Name" :	"Late Binodi Lal Bansal"},
        {"Resident Address" :	"412, Sitaram Apratments, Plot-102, I.P. Ext. Delhi-92"},
        {"Firm Name" :	"M/s. Bansal Textiles"},
        {"Office Address" :	"501, Krishna Gali, Katra Neel, Chandni Chowk, Delhi-110006"},
        {"Contact No." :	"011-42548717, 9811166550"},
        {"E-Mail" :	"amitbansal412@gmail.com"},
        {"Occupation" :	"Deals in Suiting & Shirting"},
        {"Qualification" :	"Graduate"},
        {"Nationality" :	"Indian"},
        {"Language Known" :	"Hindi, English"},
        
    ],
    [
        {"Designation" :	"Treasurer-D.H.M.A."},
        {"image" : "images/Profile_Pics/ramesh_Garg.jpg"},
        {"Name" :	"Sh. Ramesh Garg"},
        {"Father's Name" :	"Late Telu Ram Garg"},
        {"Firm" :	"M/s. Apsara Feb"},
        {"Firm Address" :	"1455/201, 2nd Floor, Shri Ram Market, Gali Chhipiyan, Maliwara, Nai Sarak, Delhi-06"},
        {"Residence Address" :	"A-12, 3rd floor, Maharana Pratap, Enclave, Pitampura-34"},
        {"Contact No." :	"011-23242377, 47511817, 9868257461"},
        {"E-mail" :	"rameshgarg.6679@gmail.com"},
        {"Occupation" : 	"Sarees"},
        {"Education Qualification" : 	"Graduate"},
        {"Nationality" : 	"Indian"},
        {"Language Known" : 	"Hindi, English"}
    ],
    [
        {"Designation" :	"Sangathan Matri-D.H.M.A."},
        {"image" : "images/Profile_Pics/Ganpat_Ahuja.jpg"},
        {"Name" :	"Sh. Ganpat Rai Ahuja"},
        {"Father's Name" :	"Late Dharam Chand Ahuja"},
        {"Firm" :	"M/s. Dharam Chand Ganpat Rai"},
        {"Firm Address" :	"9, Bagh Diwar, Fatehpuri, Chandni Chowk, Delhi-06"},
        {"Residence Address" :	"459, Sainik Vihar, Pitampura, Delhi-34"},
        {"Contact No." :	"011-45686075, 9311681555"},
        {"Occupation" : 	"Ladies Suit"},
        {"Education Qualification" : 	"Graduate"},
        {"Nationality" : 	"Indian"},
        {"Language Known" : 	"Hindi, English"}
    ],
    [
        {"Designation" :	"Prachar Matri -D.H.M.A."},
        {"image" : "images/Profile_Pics/Bharat_Jain.jpg"},
        {"Name" :	"Sh. Bharat Jain"},
        {"Father's Name" :	"Late J.K. Jain"},
        {"Firm" :	"M/s. Shree Mahavir Textiles"},
        {"Firm Address" :	"1007/1, Kucha Natwa, Chandni Chowk, Delhi-06"},
        {"Residence" :	"C-36, Radhepuri, Krishna Nagar, Delhi-51"},
        {"Contact No." :	"011-46101816, 9310001816"},
        {"Email ID" :	"bjbharti@gmail.com"},
        {"Occupation" : 	"Cloth Merchants"},
        {"Education Qualification" : 	"Graduate"},
        {"Nationality" : 	"Indian"},
        {"Language Known" : 	"Hindi, English"}
    ]
];

export default profiles;